window.LEAGUE_DATA = {
  "meta": {
    "title": "High School Boys + Ehti World Cup League",
    "updatedFrom": "Official full 104-fixture World Cup API snapshot + private league allocation",
    "pointsRule": "Win = 3, Draw = 1, Loss = 0. Sort: Points, Goal Difference, Goals For, Wins. Knockout TBC fixtures are shown but only finished known-team matches count.",
    "liveSource": "/.netlify/functions/worldcup",
    "matchCount": 104
  },
  "leaderboard": [
    {
      "Rank": 1,
      "Person": "Ahad",
      "P": 9,
      "W": 6,
      "D": 1,
      "L": 2,
      "GF": 17,
      "GA": 7,
      "GD": 10,
      "Pts": 19
    },
    {
      "Rank": 2,
      "Person": "Hood",
      "P": 9,
      "W": 5,
      "D": 1,
      "L": 3,
      "GF": 23,
      "GA": 13,
      "GD": 10,
      "Pts": 16
    },
    {
      "Rank": 3,
      "Person": "Shoeb",
      "P": 7,
      "W": 3,
      "D": 3,
      "L": 1,
      "GF": 9,
      "GA": 11,
      "GD": -2,
      "Pts": 12
    },
    {
      "Rank": 4,
      "Person": "Shahid",
      "P": 8,
      "W": 2,
      "D": 3,
      "L": 3,
      "GF": 9,
      "GA": 8,
      "GD": 1,
      "Pts": 9
    },
    {
      "Rank": 5,
      "Person": "Ehti",
      "P": 7,
      "W": 2,
      "D": 3,
      "L": 2,
      "GF": 10,
      "GA": 12,
      "GD": -2,
      "Pts": 9
    },
    {
      "Rank": 6,
      "Person": "Shafee",
      "P": 10,
      "W": 2,
      "D": 3,
      "L": 5,
      "GF": 12,
      "GA": 21,
      "GD": -9,
      "Pts": 9
    },
    {
      "Rank": 7,
      "Person": "Rasy",
      "P": 5,
      "W": 2,
      "D": 2,
      "L": 1,
      "GF": 5,
      "GA": 2,
      "GD": 3,
      "Pts": 8
    },
    {
      "Rank": 8,
      "Person": "Sabir",
      "P": 7,
      "W": 0,
      "D": 3,
      "L": 4,
      "GF": 9,
      "GA": 17,
      "GD": -8,
      "Pts": 3
    }
  ],
  "teams": [
    {
      "person": "Shoeb",
      "countries": [
        "Ghana",
        "Japan",
        "Morocco",
        "Colombia",
        "Curaçao",
        "Spain"
      ]
    },
    {
      "person": "Shahid",
      "countries": [
        "Turkey",
        "Ecuador",
        "Belgium",
        "Austria",
        "Uruguay",
        "Brazil"
      ]
    },
    {
      "person": "Ahad",
      "countries": [
        "South Korea",
        "Mexico",
        "Netherlands",
        "Scotland",
        "Norway",
        "Sweden"
      ]
    },
    {
      "person": "Ehti",
      "countries": [
        "France",
        "Tunisia",
        "Iran",
        "Congo",
        "Saudi Arabia",
        "Australia"
      ]
    },
    {
      "person": "Rasy",
      "countries": [
        "Panama",
        "Ivory Coast",
        "Egypt",
        "Bosnia and Herzegovina",
        "Argentina",
        "Cape Verde"
      ]
    },
    {
      "person": "Sabir",
      "countries": [
        "Croatia",
        "New Zealand",
        "Iraq",
        "Czechia",
        "Portugal",
        "Senegal"
      ]
    },
    {
      "person": "Hood",
      "countries": [
        "Germany",
        "Haiti",
        "England",
        "United States",
        "Switzerland",
        "Jordan"
      ]
    },
    {
      "person": "Shafee",
      "countries": [
        "South Africa",
        "Canada",
        "Uzbekistan",
        "Paraguay",
        "Algeria",
        "Qatar"
      ]
    }
  ],
  "fixtures": [
    {
      "Match #": 1,
      "Date": "2026-06-11",
      "Group": "Group A",
      "Team A": "Mexico",
      "Owner A": "",
      "Team B": "South Africa",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Mexico City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 2,
      "Score B": 0,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 2,
      "Date": "2026-06-11",
      "Group": "Group A",
      "Team A": "Korea Republic",
      "Owner A": "",
      "Team B": "Czechia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 3,
      "Date": "2026-06-12",
      "Group": "Group B",
      "Team A": "Canada",
      "Owner A": "",
      "Team B": "Bosnia and Herzegovina",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 4,
      "Date": "2026-06-12",
      "Group": "Group D",
      "Team A": "USA",
      "Owner A": "",
      "Team B": "Paraguay",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 4,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 5,
      "Date": "2026-06-13",
      "Group": "Group C",
      "Team A": "Haiti",
      "Owner A": "",
      "Team B": "Scotland",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 6,
      "Date": "2026-06-13",
      "Group": "Group D",
      "Team A": "Australia",
      "Owner A": "",
      "Team B": "Türkiye",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 7,
      "Date": "2026-06-13",
      "Group": "Group C",
      "Team A": "Brazil",
      "Owner A": "",
      "Team B": "Morocco",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 8,
      "Date": "2026-06-13",
      "Group": "Group B",
      "Team A": "Qatar",
      "Owner A": "",
      "Team B": "Switzerland",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 9,
      "Date": "2026-06-14",
      "Group": "Group E",
      "Team A": "Côte d'Ivoire",
      "Owner A": "",
      "Team B": "Ecuador",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 10,
      "Date": "2026-06-14",
      "Group": "Group E",
      "Team A": "Germany",
      "Owner A": "",
      "Team B": "Curaçao",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 7,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 11,
      "Date": "2026-06-14",
      "Group": "Group F",
      "Team A": "Netherlands",
      "Owner A": "",
      "Team B": "Japan",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 2,
      "Score B": 2,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 12,
      "Date": "2026-06-14",
      "Group": "Group F",
      "Team A": "Sweden",
      "Owner A": "",
      "Team B": "Tunisia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Monterrey",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 5,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 13,
      "Date": "2026-06-15",
      "Group": "Group H",
      "Team A": "Saudi Arabia",
      "Owner A": "",
      "Team B": "Uruguay",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 14,
      "Date": "2026-06-15",
      "Group": "Group H",
      "Team A": "Spain",
      "Owner A": "",
      "Team B": "Cabo Verde",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 15,
      "Date": "2026-06-15",
      "Group": "Group G",
      "Team A": "IR Iran",
      "Owner A": "",
      "Team B": "New Zealand",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 16,
      "Date": "2026-06-15",
      "Group": "Group G",
      "Team A": "Belgium",
      "Owner A": "",
      "Team B": "Egypt",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 17,
      "Date": "2026-06-16",
      "Group": "Group I",
      "Team A": "France",
      "Owner A": "",
      "Team B": "Senegal",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 18,
      "Date": "2026-06-16",
      "Group": "Group I",
      "Team A": "Iraq",
      "Owner A": "",
      "Team B": "Norway",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 19,
      "Date": "2026-06-16",
      "Group": "Group J",
      "Team A": "Argentina",
      "Owner A": "",
      "Team B": "Algeria",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 20,
      "Date": "2026-06-16",
      "Group": "Group J",
      "Team A": "Austria",
      "Owner A": "",
      "Team B": "Jordan",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 21,
      "Date": "2026-06-17",
      "Group": "Group L",
      "Team A": "Ghana",
      "Owner A": "",
      "Team B": "Panama",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 22,
      "Date": "2026-06-17",
      "Group": "Group L",
      "Team A": "England",
      "Owner A": "",
      "Team B": "Croatia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 4,
      "Score B": 2,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 23,
      "Date": "2026-06-17",
      "Group": "Group K",
      "Team A": "Portugal",
      "Owner A": "",
      "Team B": "Congo DR",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 24,
      "Date": "2026-06-17",
      "Group": "Group K",
      "Team A": "Uzbekistan",
      "Owner A": "",
      "Team B": "Colombia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Mexico City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 3,
      "Status": "Final",
      "Team A Pts": 0,
      "Team B Pts": 3,
      "Count?": "Yes"
    },
    {
      "Match #": 25,
      "Date": "2026-06-18",
      "Group": "Group A",
      "Team A": "Czechia",
      "Owner A": "",
      "Team B": "South Africa",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 26,
      "Date": "2026-06-18",
      "Group": "Group B",
      "Team A": "Switzerland",
      "Owner A": "",
      "Team B": "Bosnia and Herzegovina",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 27,
      "Date": "2026-06-18",
      "Group": "Group B",
      "Team A": "Canada",
      "Owner A": "",
      "Team B": "Qatar",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 28,
      "Date": "2026-06-18",
      "Group": "Group A",
      "Team A": "Mexico",
      "Owner A": "",
      "Team B": "Korea Republic",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 29,
      "Date": "2026-06-19",
      "Group": "Group C",
      "Team A": "Brazil",
      "Owner A": "",
      "Team B": "Haiti",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 30,
      "Date": "2026-06-19",
      "Group": "Group C",
      "Team A": "Scotland",
      "Owner A": "",
      "Team B": "Morocco",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 31,
      "Date": "2026-06-19",
      "Group": "Group D",
      "Team A": "Türkiye",
      "Owner A": "",
      "Team B": "Paraguay",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 32,
      "Date": "2026-06-19",
      "Group": "Group D",
      "Team A": "USA",
      "Owner A": "",
      "Team B": "Australia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 33,
      "Date": "2026-06-20",
      "Group": "Group E",
      "Team A": "Germany",
      "Owner A": "",
      "Team B": "Côte d'Ivoire",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 34,
      "Date": "2026-06-20",
      "Group": "Group E",
      "Team A": "Ecuador",
      "Owner A": "",
      "Team B": "Curaçao",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 35,
      "Date": "2026-06-20",
      "Group": "Group F",
      "Team A": "Netherlands",
      "Owner A": "",
      "Team B": "Sweden",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 36,
      "Date": "2026-06-20",
      "Group": "Group F",
      "Team A": "Tunisia",
      "Owner A": "",
      "Team B": "Japan",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Monterrey",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 37,
      "Date": "2026-06-21",
      "Group": "Group H",
      "Team A": "Uruguay",
      "Owner A": "",
      "Team B": "Cabo Verde",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 38,
      "Date": "2026-06-21",
      "Group": "Group H",
      "Team A": "Spain",
      "Owner A": "",
      "Team B": "Saudi Arabia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 39,
      "Date": "2026-06-21",
      "Group": "Group G",
      "Team A": "Belgium",
      "Owner A": "",
      "Team B": "IR Iran",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 40,
      "Date": "2026-06-21",
      "Group": "Group G",
      "Team A": "New Zealand",
      "Owner A": "",
      "Team B": "Egypt",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 41,
      "Date": "2026-06-22",
      "Group": "Group I",
      "Team A": "Norway",
      "Owner A": "",
      "Team B": "Senegal",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 42,
      "Date": "2026-06-22",
      "Group": "Group I",
      "Team A": "France",
      "Owner A": "",
      "Team B": "Iraq",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 43,
      "Date": "2026-06-22",
      "Group": "Group J",
      "Team A": "Argentina",
      "Owner A": "",
      "Team B": "Austria",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 44,
      "Date": "2026-06-22",
      "Group": "Group J",
      "Team A": "Jordan",
      "Owner A": "",
      "Team B": "Algeria",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 45,
      "Date": "2026-06-23",
      "Group": "Group L",
      "Team A": "England",
      "Owner A": "",
      "Team B": "Ghana",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 46,
      "Date": "2026-06-23",
      "Group": "Group L",
      "Team A": "Panama",
      "Owner A": "",
      "Team B": "Croatia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 47,
      "Date": "2026-06-23",
      "Group": "Group K",
      "Team A": "Portugal",
      "Owner A": "",
      "Team B": "Uzbekistan",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 48,
      "Date": "2026-06-23",
      "Group": "Group K",
      "Team A": "Colombia",
      "Owner A": "",
      "Team B": "Congo DR",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 49,
      "Date": "2026-06-24",
      "Group": "Group C",
      "Team A": "Scotland",
      "Owner A": "",
      "Team B": "Brazil",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 50,
      "Date": "2026-06-24",
      "Group": "Group C",
      "Team A": "Morocco",
      "Owner A": "",
      "Team B": "Haiti",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 51,
      "Date": "2026-06-24",
      "Group": "Group B",
      "Team A": "Switzerland",
      "Owner A": "",
      "Team B": "Canada",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 52,
      "Date": "2026-06-24",
      "Group": "Group B",
      "Team A": "Bosnia and Herzegovina",
      "Owner A": "",
      "Team B": "Qatar",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 53,
      "Date": "2026-06-24",
      "Group": "Group A",
      "Team A": "Czechia",
      "Owner A": "",
      "Team B": "Mexico",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Mexico City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 54,
      "Date": "2026-06-24",
      "Group": "Group A",
      "Team A": "South Africa",
      "Owner A": "",
      "Team B": "Korea Republic",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Monterrey",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 55,
      "Date": "2026-06-25",
      "Group": "Group E",
      "Team A": "Curaçao",
      "Owner A": "",
      "Team B": "Côte d'Ivoire",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 56,
      "Date": "2026-06-25",
      "Group": "Group E",
      "Team A": "Ecuador",
      "Owner A": "",
      "Team B": "Germany",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 57,
      "Date": "2026-06-25",
      "Group": "Group F",
      "Team A": "Japan",
      "Owner A": "",
      "Team B": "Sweden",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 58,
      "Date": "2026-06-25",
      "Group": "Group F",
      "Team A": "Tunisia",
      "Owner A": "",
      "Team B": "Netherlands",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 59,
      "Date": "2026-06-25",
      "Group": "Group D",
      "Team A": "Türkiye",
      "Owner A": "",
      "Team B": "USA",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 60,
      "Date": "2026-06-25",
      "Group": "Group D",
      "Team A": "Paraguay",
      "Owner A": "",
      "Team B": "Australia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 61,
      "Date": "2026-06-26",
      "Group": "Group I",
      "Team A": "Norway",
      "Owner A": "",
      "Team B": "France",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 62,
      "Date": "2026-06-26",
      "Group": "Group I",
      "Team A": "Senegal",
      "Owner A": "",
      "Team B": "Iraq",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 63,
      "Date": "2026-06-26",
      "Group": "Group G",
      "Team A": "Egypt",
      "Owner A": "",
      "Team B": "IR Iran",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 64,
      "Date": "2026-06-26",
      "Group": "Group G",
      "Team A": "New Zealand",
      "Owner A": "",
      "Team B": "Belgium",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 65,
      "Date": "2026-06-26",
      "Group": "Group H",
      "Team A": "Cabo Verde",
      "Owner A": "",
      "Team B": "Saudi Arabia",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 66,
      "Date": "2026-06-26",
      "Group": "Group H",
      "Team A": "Uruguay",
      "Owner A": "",
      "Team B": "Spain",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 67,
      "Date": "2026-06-27",
      "Group": "Group L",
      "Team A": "Panama",
      "Owner A": "",
      "Team B": "England",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 68,
      "Date": "2026-06-27",
      "Group": "Group L",
      "Team A": "Croatia",
      "Owner A": "",
      "Team B": "Ghana",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 69,
      "Date": "2026-06-27",
      "Group": "Group J",
      "Team A": "Algeria",
      "Owner A": "",
      "Team B": "Austria",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 70,
      "Date": "2026-06-27",
      "Group": "Group J",
      "Team A": "Jordan",
      "Owner A": "",
      "Team B": "Argentina",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 71,
      "Date": "2026-06-27",
      "Group": "Group K",
      "Team A": "Colombia",
      "Owner A": "",
      "Team B": "Portugal",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 72,
      "Date": "2026-06-27",
      "Group": "Group K",
      "Team A": "Congo DR",
      "Owner A": "",
      "Team B": "Uzbekistan",
      "Owner B": "",
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": "",
      "Score B": "",
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    }
  ],
  "matches": [
    {
      "ApiId": 537327,
      "DateISO": "2026-06-11T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Mexico",
      "Home Owner": "Ahad",
      "Home Goals": 2,
      "Away Goals": 0,
      "Away Owner": "Shafee",
      "Away Team": "South Africa",
      "Group": "Group A",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 1
    },
    {
      "ApiId": 537328,
      "DateISO": "2026-06-12T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "South Korea",
      "Home Owner": "Ahad",
      "Home Goals": 2,
      "Away Goals": 1,
      "Away Owner": "Sabir",
      "Away Team": "Czechia",
      "Group": "Group A",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 2
    },
    {
      "ApiId": 537333,
      "DateISO": "2026-06-12T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Canada",
      "Home Owner": "Shafee",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Rasy",
      "Away Team": "Bosnia and Herzegovina",
      "Group": "Group B",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 3
    },
    {
      "ApiId": 537345,
      "DateISO": "2026-06-13T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "United States",
      "Home Owner": "Hood",
      "Home Goals": 4,
      "Away Goals": 1,
      "Away Owner": "Shafee",
      "Away Team": "Paraguay",
      "Group": "Group D",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 4
    },
    {
      "ApiId": 537334,
      "DateISO": "2026-06-13T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Qatar",
      "Home Owner": "Shafee",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Hood",
      "Away Team": "Switzerland",
      "Group": "Group B",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 5
    },
    {
      "ApiId": 537339,
      "DateISO": "2026-06-13T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Brazil",
      "Home Owner": "Shahid",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Shoeb",
      "Away Team": "Morocco",
      "Group": "Group C",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 6
    },
    {
      "ApiId": 537340,
      "DateISO": "2026-06-14T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Haiti",
      "Home Owner": "Hood",
      "Home Goals": 0,
      "Away Goals": 1,
      "Away Owner": "Ahad",
      "Away Team": "Scotland",
      "Group": "Group C",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 7
    },
    {
      "ApiId": 537346,
      "DateISO": "2026-06-14T04:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Australia",
      "Home Owner": "Ehti",
      "Home Goals": 2,
      "Away Goals": 0,
      "Away Owner": "Shahid",
      "Away Team": "Turkey",
      "Group": "Group D",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 8
    },
    {
      "ApiId": 537351,
      "DateISO": "2026-06-14T17:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Germany",
      "Home Owner": "Hood",
      "Home Goals": 7,
      "Away Goals": 1,
      "Away Owner": "Shoeb",
      "Away Team": "Curaçao",
      "Group": "Group E",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 9
    },
    {
      "ApiId": 537357,
      "DateISO": "2026-06-14T20:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Netherlands",
      "Home Owner": "Ahad",
      "Home Goals": 2,
      "Away Goals": 2,
      "Away Owner": "Shoeb",
      "Away Team": "Japan",
      "Group": "Group F",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 10
    },
    {
      "ApiId": 537352,
      "DateISO": "2026-06-14T23:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Ivory Coast",
      "Home Owner": "Rasy",
      "Home Goals": 1,
      "Away Goals": 0,
      "Away Owner": "Shahid",
      "Away Team": "Ecuador",
      "Group": "Group E",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 11
    },
    {
      "ApiId": 537358,
      "DateISO": "2026-06-15T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Sweden",
      "Home Owner": "Ahad",
      "Home Goals": 5,
      "Away Goals": 1,
      "Away Owner": "Ehti",
      "Away Team": "Tunisia",
      "Group": "Group F",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 12
    },
    {
      "ApiId": 537369,
      "DateISO": "2026-06-15T16:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Spain",
      "Home Owner": "Shoeb",
      "Home Goals": 0,
      "Away Goals": 0,
      "Away Owner": "Rasy",
      "Away Team": "Cape Verde",
      "Group": "Group H",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 13
    },
    {
      "ApiId": 537363,
      "DateISO": "2026-06-15T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Belgium",
      "Home Owner": "Shahid",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Rasy",
      "Away Team": "Egypt",
      "Group": "Group G",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 14
    },
    {
      "ApiId": 537370,
      "DateISO": "2026-06-15T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Saudi Arabia",
      "Home Owner": "Ehti",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Shahid",
      "Away Team": "Uruguay",
      "Group": "Group H",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 15
    },
    {
      "ApiId": 537364,
      "DateISO": "2026-06-16T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Iran",
      "Home Owner": "Ehti",
      "Home Goals": 2,
      "Away Goals": 2,
      "Away Owner": "Sabir",
      "Away Team": "New Zealand",
      "Group": "Group G",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 16
    },
    {
      "ApiId": 537391,
      "DateISO": "2026-06-16T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "France",
      "Home Owner": "Ehti",
      "Home Goals": 3,
      "Away Goals": 1,
      "Away Owner": "Sabir",
      "Away Team": "Senegal",
      "Group": "Group I",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 17
    },
    {
      "ApiId": 537392,
      "DateISO": "2026-06-16T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Iraq",
      "Home Owner": "Sabir",
      "Home Goals": 1,
      "Away Goals": 4,
      "Away Owner": "Ahad",
      "Away Team": "Norway",
      "Group": "Group I",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 18
    },
    {
      "ApiId": 537397,
      "DateISO": "2026-06-17T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Argentina",
      "Home Owner": "Rasy",
      "Home Goals": 3,
      "Away Goals": 0,
      "Away Owner": "Shafee",
      "Away Team": "Algeria",
      "Group": "Group J",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 19
    },
    {
      "ApiId": 537398,
      "DateISO": "2026-06-17T04:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Austria",
      "Home Owner": "Shahid",
      "Home Goals": 3,
      "Away Goals": 1,
      "Away Owner": "Hood",
      "Away Team": "Jordan",
      "Group": "Group J",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 20
    },
    {
      "ApiId": 537403,
      "DateISO": "2026-06-17T17:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Portugal",
      "Home Owner": "Sabir",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Ehti",
      "Away Team": "Congo",
      "Group": "Group K",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 21
    },
    {
      "ApiId": 537409,
      "DateISO": "2026-06-17T20:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "England",
      "Home Owner": "Hood",
      "Home Goals": 4,
      "Away Goals": 2,
      "Away Owner": "Sabir",
      "Away Team": "Croatia",
      "Group": "Group L",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 22
    },
    {
      "ApiId": 537410,
      "DateISO": "2026-06-17T23:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Ghana",
      "Home Owner": "Shoeb",
      "Home Goals": 1,
      "Away Goals": 0,
      "Away Owner": "Rasy",
      "Away Team": "Panama",
      "Group": "Group L",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 23
    },
    {
      "ApiId": 537404,
      "DateISO": "2026-06-18T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Uzbekistan",
      "Home Owner": "Shafee",
      "Home Goals": 1,
      "Away Goals": 3,
      "Away Owner": "Shoeb",
      "Away Team": "Colombia",
      "Group": "Group K",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 24
    },
    {
      "ApiId": 537329,
      "DateISO": "2026-06-18T16:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Czechia",
      "Home Owner": "Sabir",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Shafee",
      "Away Team": "South Africa",
      "Group": "Group A",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 25
    },
    {
      "ApiId": 537335,
      "DateISO": "2026-06-18T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Switzerland",
      "Home Owner": "Hood",
      "Home Goals": 4,
      "Away Goals": 1,
      "Away Owner": "Rasy",
      "Away Team": "Bosnia and Herzegovina",
      "Group": "Group B",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 26
    },
    {
      "ApiId": 537336,
      "DateISO": "2026-06-18T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Canada",
      "Home Owner": "Shafee",
      "Home Goals": 6,
      "Away Goals": 0,
      "Away Owner": "Shafee",
      "Away Team": "Qatar",
      "Group": "Group B",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 27
    },
    {
      "ApiId": 537330,
      "DateISO": "2026-06-19T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Mexico",
      "Home Owner": "Ahad",
      "Home Goals": 1,
      "Away Goals": 0,
      "Away Owner": "Ahad",
      "Away Team": "South Korea",
      "Group": "Group A",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 28
    },
    {
      "ApiId": 537348,
      "DateISO": "2026-06-19T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "United States",
      "Home Owner": "Hood",
      "Home Goals": 2,
      "Away Goals": 0,
      "Away Owner": "Ehti",
      "Away Team": "Australia",
      "Group": "Group D",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 29
    },
    {
      "ApiId": 537342,
      "DateISO": "2026-06-19T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Scotland",
      "Home Owner": "Ahad",
      "Home Goals": 0,
      "Away Goals": 1,
      "Away Owner": "Shoeb",
      "Away Team": "Morocco",
      "Group": "Group C",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 30
    },
    {
      "ApiId": 537341,
      "DateISO": "2026-06-20T00:30:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Brazil",
      "Home Owner": "Shahid",
      "Home Goals": 3,
      "Away Goals": 0,
      "Away Owner": "Hood",
      "Away Team": "Haiti",
      "Group": "Group C",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 31
    },
    {
      "ApiId": 537347,
      "DateISO": "2026-06-20T03:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Turkey",
      "Home Owner": "Shahid",
      "Home Goals": 0,
      "Away Goals": 1,
      "Away Owner": "Shafee",
      "Away Team": "Paraguay",
      "Group": "Group D",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 32
    },
    {
      "ApiId": 537359,
      "DateISO": "2026-06-20T17:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Netherlands",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Sweden",
      "Group": "Group F",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 33
    },
    {
      "ApiId": 537353,
      "DateISO": "2026-06-20T20:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Germany",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Ivory Coast",
      "Group": "Group E",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 34
    },
    {
      "ApiId": 537354,
      "DateISO": "2026-06-21T00:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Ecuador",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Curaçao",
      "Group": "Group E",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 35
    },
    {
      "ApiId": 537360,
      "DateISO": "2026-06-21T04:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Tunisia",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Japan",
      "Group": "Group F",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 36
    },
    {
      "ApiId": 537371,
      "DateISO": "2026-06-21T16:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Spain",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Saudi Arabia",
      "Group": "Group H",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 37
    },
    {
      "ApiId": 537365,
      "DateISO": "2026-06-21T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Belgium",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Iran",
      "Group": "Group G",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 38
    },
    {
      "ApiId": 537372,
      "DateISO": "2026-06-21T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Uruguay",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Cape Verde",
      "Group": "Group H",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 39
    },
    {
      "ApiId": 537366,
      "DateISO": "2026-06-22T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "New Zealand",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Egypt",
      "Group": "Group G",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 40
    },
    {
      "ApiId": 537399,
      "DateISO": "2026-06-22T17:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Argentina",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Austria",
      "Group": "Group J",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 41
    },
    {
      "ApiId": 537393,
      "DateISO": "2026-06-22T21:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "France",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Iraq",
      "Group": "Group I",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 42
    },
    {
      "ApiId": 537394,
      "DateISO": "2026-06-23T00:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Norway",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Senegal",
      "Group": "Group I",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 43
    },
    {
      "ApiId": 537400,
      "DateISO": "2026-06-23T03:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Jordan",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Algeria",
      "Group": "Group J",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 44
    },
    {
      "ApiId": 537405,
      "DateISO": "2026-06-23T17:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Portugal",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Uzbekistan",
      "Group": "Group K",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 45
    },
    {
      "ApiId": 537411,
      "DateISO": "2026-06-23T20:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "England",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Ghana",
      "Group": "Group L",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 46
    },
    {
      "ApiId": 537412,
      "DateISO": "2026-06-23T23:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Panama",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Croatia",
      "Group": "Group L",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 47
    },
    {
      "ApiId": 537406,
      "DateISO": "2026-06-24T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Colombia",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Congo",
      "Group": "Group K",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 48
    },
    {
      "ApiId": 537337,
      "DateISO": "2026-06-24T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Switzerland",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Canada",
      "Group": "Group B",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 49
    },
    {
      "ApiId": 537338,
      "DateISO": "2026-06-24T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Bosnia and Herzegovina",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Qatar",
      "Group": "Group B",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 50
    },
    {
      "ApiId": 537344,
      "DateISO": "2026-06-24T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Morocco",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "Haiti",
      "Group": "Group C",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 51
    },
    {
      "ApiId": 537343,
      "DateISO": "2026-06-24T22:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Scotland",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Brazil",
      "Group": "Group C",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 52
    },
    {
      "ApiId": 537331,
      "DateISO": "2026-06-25T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Czechia",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Mexico",
      "Group": "Group A",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 53
    },
    {
      "ApiId": 537332,
      "DateISO": "2026-06-25T01:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "South Africa",
      "Home Owner": "Shafee",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "South Korea",
      "Group": "Group A",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 54
    },
    {
      "ApiId": 537355,
      "DateISO": "2026-06-25T20:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Ecuador",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "Germany",
      "Group": "Group E",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 55
    },
    {
      "ApiId": 537356,
      "DateISO": "2026-06-25T20:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Curaçao",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Ivory Coast",
      "Group": "Group E",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 56
    },
    {
      "ApiId": 537361,
      "DateISO": "2026-06-25T23:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Tunisia",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Netherlands",
      "Group": "Group F",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 57
    },
    {
      "ApiId": 537362,
      "DateISO": "2026-06-25T23:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Japan",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Sweden",
      "Group": "Group F",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 58
    },
    {
      "ApiId": 537349,
      "DateISO": "2026-06-26T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Turkey",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "United States",
      "Group": "Group D",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 59
    },
    {
      "ApiId": 537350,
      "DateISO": "2026-06-26T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Paraguay",
      "Home Owner": "Shafee",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Australia",
      "Group": "Group D",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 60
    },
    {
      "ApiId": 537395,
      "DateISO": "2026-06-26T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Norway",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "France",
      "Group": "Group I",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 61
    },
    {
      "ApiId": 537396,
      "DateISO": "2026-06-26T19:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Senegal",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Iraq",
      "Group": "Group I",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 62
    },
    {
      "ApiId": 537373,
      "DateISO": "2026-06-27T00:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Uruguay",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Spain",
      "Group": "Group H",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 63
    },
    {
      "ApiId": 537374,
      "DateISO": "2026-06-27T00:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Cape Verde",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Saudi Arabia",
      "Group": "Group H",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 64
    },
    {
      "ApiId": 537367,
      "DateISO": "2026-06-27T03:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "New Zealand",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Belgium",
      "Group": "Group G",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 65
    },
    {
      "ApiId": 537368,
      "DateISO": "2026-06-27T03:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Egypt",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Iran",
      "Group": "Group G",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 66
    },
    {
      "ApiId": 537413,
      "DateISO": "2026-06-27T21:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Panama",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "England",
      "Group": "Group L",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 67
    },
    {
      "ApiId": 537414,
      "DateISO": "2026-06-27T21:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Croatia",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Ghana",
      "Group": "Group L",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 68
    },
    {
      "ApiId": 537407,
      "DateISO": "2026-06-27T23:30:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Colombia",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Portugal",
      "Group": "Group K",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 69
    },
    {
      "ApiId": 537408,
      "DateISO": "2026-06-27T23:30:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Congo",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Uzbekistan",
      "Group": "Group K",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 70
    },
    {
      "ApiId": 537401,
      "DateISO": "2026-06-28T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Jordan",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Argentina",
      "Group": "Group J",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 71
    },
    {
      "ApiId": 537402,
      "DateISO": "2026-06-28T02:00:00Z",
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Algeria",
      "Home Owner": "Shafee",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Austria",
      "Group": "Group J",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 72
    },
    {
      "ApiId": 537417,
      "DateISO": "2026-06-28T19:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 73
    },
    {
      "ApiId": 537423,
      "DateISO": "2026-06-29T17:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 74
    },
    {
      "ApiId": 537415,
      "DateISO": "2026-06-29T20:30:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 75
    },
    {
      "ApiId": 537418,
      "DateISO": "2026-06-30T01:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 76
    },
    {
      "ApiId": 537424,
      "DateISO": "2026-06-30T17:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 77
    },
    {
      "ApiId": 537416,
      "DateISO": "2026-06-30T21:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 78
    },
    {
      "ApiId": 537425,
      "DateISO": "2026-07-01T01:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 79
    },
    {
      "ApiId": 537426,
      "DateISO": "2026-07-01T16:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 80
    },
    {
      "ApiId": 537422,
      "DateISO": "2026-07-01T20:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 81
    },
    {
      "ApiId": 537421,
      "DateISO": "2026-07-02T00:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 82
    },
    {
      "ApiId": 537420,
      "DateISO": "2026-07-02T19:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 83
    },
    {
      "ApiId": 537419,
      "DateISO": "2026-07-02T23:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 84
    },
    {
      "ApiId": 537429,
      "DateISO": "2026-07-03T03:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 85
    },
    {
      "ApiId": 537428,
      "DateISO": "2026-07-03T18:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 86
    },
    {
      "ApiId": 537427,
      "DateISO": "2026-07-03T22:00:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 87
    },
    {
      "ApiId": 537430,
      "DateISO": "2026-07-04T01:30:00Z",
      "Stage": "LAST_32",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 32",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 88
    },
    {
      "ApiId": 537376,
      "DateISO": "2026-07-04T17:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 89
    },
    {
      "ApiId": 537375,
      "DateISO": "2026-07-04T21:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 90
    },
    {
      "ApiId": 537377,
      "DateISO": "2026-07-05T20:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 91
    },
    {
      "ApiId": 537378,
      "DateISO": "2026-07-06T00:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 92
    },
    {
      "ApiId": 537379,
      "DateISO": "2026-07-06T19:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 93
    },
    {
      "ApiId": 537380,
      "DateISO": "2026-07-07T00:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 94
    },
    {
      "ApiId": 537381,
      "DateISO": "2026-07-07T16:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 95
    },
    {
      "ApiId": 537382,
      "DateISO": "2026-07-07T20:00:00Z",
      "Stage": "LAST_16",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Last 16",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 96
    },
    {
      "ApiId": 537383,
      "DateISO": "2026-07-09T20:00:00Z",
      "Stage": "QUARTER_FINALS",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Quarter Finals",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 97
    },
    {
      "ApiId": 537384,
      "DateISO": "2026-07-10T19:00:00Z",
      "Stage": "QUARTER_FINALS",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Quarter Finals",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 98
    },
    {
      "ApiId": 537385,
      "DateISO": "2026-07-11T21:00:00Z",
      "Stage": "QUARTER_FINALS",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Quarter Finals",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 99
    },
    {
      "ApiId": 537386,
      "DateISO": "2026-07-12T01:00:00Z",
      "Stage": "QUARTER_FINALS",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Quarter Finals",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 100
    },
    {
      "ApiId": 537387,
      "DateISO": "2026-07-14T19:00:00Z",
      "Stage": "SEMI_FINALS",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Semi Finals",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 101
    },
    {
      "ApiId": 537388,
      "DateISO": "2026-07-15T19:00:00Z",
      "Stage": "SEMI_FINALS",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Semi Finals",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 102
    },
    {
      "ApiId": 537389,
      "DateISO": "2026-07-18T21:00:00Z",
      "Stage": "THIRD_PLACE",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Third Place",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 103
    },
    {
      "ApiId": 537390,
      "DateISO": "2026-07-19T19:00:00Z",
      "Stage": "FINAL",
      "Status": "TIMED",
      "Home Team": "TBC",
      "Home Owner": "",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "",
      "Away Team": "TBC",
      "Group": "Final",
      "Venue": "",
      "Competition": "FIFA World Cup 2026",
      "Match #": 104
    }
  ]
};
