window.LEAGUE_DATA = {
  "meta": {
    "title": "High School Boys + Ehti World Cup League",
    "updatedFrom": "world_cup_boys_auto_league_tracker(2).xlsx",
    "pointsRule": "Win = 3, Draw = 1, Loss = 0. Sort: Points, Goal Difference, Goals For, Wins."
  },
  "leaderboard": [
    {
      "Rank": 1,
      "Person": "Ahad",
      "P": 9,
      "W": 6,
      "D": 1,
      "L": 2,
      "GF": 17,
      "GA": 7,
      "GD": 10,
      "Pts": 19
    },
    {
      "Rank": 2,
      "Person": "Hood",
      "P": 9,
      "W": 5,
      "D": 1,
      "L": 3,
      "GF": 23,
      "GA": 13,
      "GD": 10,
      "Pts": 16
    },
    {
      "Rank": 3,
      "Person": "Shoeb",
      "P": 7,
      "W": 3,
      "D": 3,
      "L": 1,
      "GF": 9,
      "GA": 11,
      "GD": -2,
      "Pts": 12
    },
    {
      "Rank": 4,
      "Person": "Shahid",
      "P": 8,
      "W": 2,
      "D": 3,
      "L": 3,
      "GF": 9,
      "GA": 8,
      "GD": 1,
      "Pts": 9
    },
    {
      "Rank": 5,
      "Person": "Ehti",
      "P": 7,
      "W": 2,
      "D": 3,
      "L": 2,
      "GF": 10,
      "GA": 12,
      "GD": -2,
      "Pts": 9
    },
    {
      "Rank": 6,
      "Person": "Shafee",
      "P": 10,
      "W": 2,
      "D": 3,
      "L": 5,
      "GF": 12,
      "GA": 21,
      "GD": -9,
      "Pts": 9
    },
    {
      "Rank": 7,
      "Person": "Rasy",
      "P": 5,
      "W": 2,
      "D": 2,
      "L": 1,
      "GF": 5,
      "GA": 2,
      "GD": 3,
      "Pts": 8
    },
    {
      "Rank": 8,
      "Person": "Sabir",
      "P": 7,
      "W": 0,
      "D": 3,
      "L": 4,
      "GF": 9,
      "GA": 17,
      "GD": -8,
      "Pts": 3
    }
  ],
  "teams": [
    {
      "person": "Shoeb",
      "countries": [
        "Ghana",
        "Japan",
        "Morocco",
        "Colombia",
        "Curaçao",
        "Spain"
      ]
    },
    {
      "person": "Shahid",
      "countries": [
        "Turkey",
        "Ecuador",
        "Belgium",
        "Austria",
        "Uruguay",
        "Brazil"
      ]
    },
    {
      "person": "Ahad",
      "countries": [
        "South Korea",
        "Mexico",
        "Netherlands",
        "Scotland",
        "Norway",
        "Sweden"
      ]
    },
    {
      "person": "Ehti",
      "countries": [
        "France",
        "Tunisia",
        "Iran",
        "Congo",
        "Saudi Arabia",
        "Australia"
      ]
    },
    {
      "person": "Rasy",
      "countries": [
        "Panama",
        "Ivory Coast",
        "Egypt",
        "Bosnia and Herzegovina",
        "Argentina",
        "Cape Verde"
      ]
    },
    {
      "person": "Sabir",
      "countries": [
        "Croatia",
        "New Zealand",
        "Iraq",
        "Czechia",
        "Portugal",
        "Senegal"
      ]
    },
    {
      "person": "Hood",
      "countries": [
        "Germany",
        "Haiti",
        "England",
        "United States",
        "Switzerland",
        "Jordan"
      ]
    },
    {
      "person": "Shafee",
      "countries": [
        "South Africa",
        "Canada",
        "Uzbekistan",
        "Paraguay",
        "Algeria",
        "Qatar"
      ]
    }
  ],
  "fixtures": [
    {
      "Match #": 1,
      "Date": "2026-06-11",
      "Group": "Group A",
      "Team A": "Mexico",
      "Owner A": null,
      "Team B": "South Africa",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Mexico City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 2,
      "Score B": 0,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 2,
      "Date": "2026-06-11",
      "Group": "Group A",
      "Team A": "Korea Republic",
      "Owner A": null,
      "Team B": "Czechia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 3,
      "Date": "2026-06-12",
      "Group": "Group B",
      "Team A": "Canada",
      "Owner A": null,
      "Team B": "Bosnia and Herzegovina",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 4,
      "Date": "2026-06-12",
      "Group": "Group D",
      "Team A": "USA",
      "Owner A": null,
      "Team B": "Paraguay",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 4,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 5,
      "Date": "2026-06-13",
      "Group": "Group C",
      "Team A": "Haiti",
      "Owner A": null,
      "Team B": "Scotland",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 6,
      "Date": "2026-06-13",
      "Group": "Group D",
      "Team A": "Australia",
      "Owner A": null,
      "Team B": "Türkiye",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 7,
      "Date": "2026-06-13",
      "Group": "Group C",
      "Team A": "Brazil",
      "Owner A": null,
      "Team B": "Morocco",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 8,
      "Date": "2026-06-13",
      "Group": "Group B",
      "Team A": "Qatar",
      "Owner A": null,
      "Team B": "Switzerland",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 9,
      "Date": "2026-06-14",
      "Group": "Group E",
      "Team A": "Côte d'Ivoire",
      "Owner A": null,
      "Team B": "Ecuador",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 10,
      "Date": "2026-06-14",
      "Group": "Group E",
      "Team A": "Germany",
      "Owner A": null,
      "Team B": "Curaçao",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 7,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 11,
      "Date": "2026-06-14",
      "Group": "Group F",
      "Team A": "Netherlands",
      "Owner A": null,
      "Team B": "Japan",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 2,
      "Score B": 2,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 12,
      "Date": "2026-06-14",
      "Group": "Group F",
      "Team A": "Sweden",
      "Owner A": null,
      "Team B": "Tunisia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Monterrey",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 5,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 13,
      "Date": "2026-06-15",
      "Group": "Group H",
      "Team A": "Saudi Arabia",
      "Owner A": null,
      "Team B": "Uruguay",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 14,
      "Date": "2026-06-15",
      "Group": "Group H",
      "Team A": "Spain",
      "Owner A": null,
      "Team B": "Cabo Verde",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 15,
      "Date": "2026-06-15",
      "Group": "Group G",
      "Team A": "IR Iran",
      "Owner A": null,
      "Team B": "New Zealand",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 16,
      "Date": "2026-06-15",
      "Group": "Group G",
      "Team A": "Belgium",
      "Owner A": null,
      "Team B": "Egypt",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 17,
      "Date": "2026-06-16",
      "Group": "Group I",
      "Team A": "France",
      "Owner A": null,
      "Team B": "Senegal",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 18,
      "Date": "2026-06-16",
      "Group": "Group I",
      "Team A": "Iraq",
      "Owner A": null,
      "Team B": "Norway",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 19,
      "Date": "2026-06-16",
      "Group": "Group J",
      "Team A": "Argentina",
      "Owner A": null,
      "Team B": "Algeria",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 20,
      "Date": "2026-06-16",
      "Group": "Group J",
      "Team A": "Austria",
      "Owner A": null,
      "Team B": "Jordan",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 21,
      "Date": "2026-06-17",
      "Group": "Group L",
      "Team A": "Ghana",
      "Owner A": null,
      "Team B": "Panama",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 22,
      "Date": "2026-06-17",
      "Group": "Group L",
      "Team A": "England",
      "Owner A": null,
      "Team B": "Croatia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 4,
      "Score B": 2,
      "Status": "Final",
      "Team A Pts": 3,
      "Team B Pts": 0,
      "Count?": "Yes"
    },
    {
      "Match #": 23,
      "Date": "2026-06-17",
      "Group": "Group K",
      "Team A": "Portugal",
      "Owner A": null,
      "Team B": "Congo DR",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 1,
      "Status": "Final",
      "Team A Pts": 1,
      "Team B Pts": 1,
      "Count?": "Yes"
    },
    {
      "Match #": 24,
      "Date": "2026-06-17",
      "Group": "Group K",
      "Team A": "Uzbekistan",
      "Owner A": null,
      "Team B": "Colombia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Mexico City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": 1,
      "Score B": 3,
      "Status": "Final",
      "Team A Pts": 0,
      "Team B Pts": 3,
      "Count?": "Yes"
    },
    {
      "Match #": 25,
      "Date": "2026-06-18",
      "Group": "Group A",
      "Team A": "Czechia",
      "Owner A": null,
      "Team B": "South Africa",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 26,
      "Date": "2026-06-18",
      "Group": "Group B",
      "Team A": "Switzerland",
      "Owner A": null,
      "Team B": "Bosnia and Herzegovina",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 27,
      "Date": "2026-06-18",
      "Group": "Group B",
      "Team A": "Canada",
      "Owner A": null,
      "Team B": "Qatar",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 28,
      "Date": "2026-06-18",
      "Group": "Group A",
      "Team A": "Mexico",
      "Owner A": null,
      "Team B": "Korea Republic",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 29,
      "Date": "2026-06-19",
      "Group": "Group C",
      "Team A": "Brazil",
      "Owner A": null,
      "Team B": "Haiti",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 30,
      "Date": "2026-06-19",
      "Group": "Group C",
      "Team A": "Scotland",
      "Owner A": null,
      "Team B": "Morocco",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 31,
      "Date": "2026-06-19",
      "Group": "Group D",
      "Team A": "Türkiye",
      "Owner A": null,
      "Team B": "Paraguay",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 32,
      "Date": "2026-06-19",
      "Group": "Group D",
      "Team A": "USA",
      "Owner A": null,
      "Team B": "Australia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 33,
      "Date": "2026-06-20",
      "Group": "Group E",
      "Team A": "Germany",
      "Owner A": null,
      "Team B": "Côte d'Ivoire",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 34,
      "Date": "2026-06-20",
      "Group": "Group E",
      "Team A": "Ecuador",
      "Owner A": null,
      "Team B": "Curaçao",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 35,
      "Date": "2026-06-20",
      "Group": "Group F",
      "Team A": "Netherlands",
      "Owner A": null,
      "Team B": "Sweden",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 36,
      "Date": "2026-06-20",
      "Group": "Group F",
      "Team A": "Tunisia",
      "Owner A": null,
      "Team B": "Japan",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Monterrey",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 37,
      "Date": "2026-06-21",
      "Group": "Group H",
      "Team A": "Uruguay",
      "Owner A": null,
      "Team B": "Cabo Verde",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 38,
      "Date": "2026-06-21",
      "Group": "Group H",
      "Team A": "Spain",
      "Owner A": null,
      "Team B": "Saudi Arabia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 39,
      "Date": "2026-06-21",
      "Group": "Group G",
      "Team A": "Belgium",
      "Owner A": null,
      "Team B": "IR Iran",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 40,
      "Date": "2026-06-21",
      "Group": "Group G",
      "Team A": "New Zealand",
      "Owner A": null,
      "Team B": "Egypt",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 41,
      "Date": "2026-06-22",
      "Group": "Group I",
      "Team A": "Norway",
      "Owner A": null,
      "Team B": "Senegal",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 42,
      "Date": "2026-06-22",
      "Group": "Group I",
      "Team A": "France",
      "Owner A": null,
      "Team B": "Iraq",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 43,
      "Date": "2026-06-22",
      "Group": "Group J",
      "Team A": "Argentina",
      "Owner A": null,
      "Team B": "Austria",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 44,
      "Date": "2026-06-22",
      "Group": "Group J",
      "Team A": "Jordan",
      "Owner A": null,
      "Team B": "Algeria",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 45,
      "Date": "2026-06-23",
      "Group": "Group L",
      "Team A": "England",
      "Owner A": null,
      "Team B": "Ghana",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 46,
      "Date": "2026-06-23",
      "Group": "Group L",
      "Team A": "Panama",
      "Owner A": null,
      "Team B": "Croatia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 47,
      "Date": "2026-06-23",
      "Group": "Group K",
      "Team A": "Portugal",
      "Owner A": null,
      "Team B": "Uzbekistan",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 48,
      "Date": "2026-06-23",
      "Group": "Group K",
      "Team A": "Colombia",
      "Owner A": null,
      "Team B": "Congo DR",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 49,
      "Date": "2026-06-24",
      "Group": "Group C",
      "Team A": "Scotland",
      "Owner A": null,
      "Team B": "Brazil",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 50,
      "Date": "2026-06-24",
      "Group": "Group C",
      "Team A": "Morocco",
      "Owner A": null,
      "Team B": "Haiti",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 51,
      "Date": "2026-06-24",
      "Group": "Group B",
      "Team A": "Switzerland",
      "Owner A": null,
      "Team B": "Canada",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 52,
      "Date": "2026-06-24",
      "Group": "Group B",
      "Team A": "Bosnia and Herzegovina",
      "Owner A": null,
      "Team B": "Qatar",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 53,
      "Date": "2026-06-24",
      "Group": "Group A",
      "Team A": "Czechia",
      "Owner A": null,
      "Team B": "Mexico",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Mexico City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 54,
      "Date": "2026-06-24",
      "Group": "Group A",
      "Team A": "South Africa",
      "Owner A": null,
      "Team B": "Korea Republic",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Monterrey",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 55,
      "Date": "2026-06-25",
      "Group": "Group E",
      "Team A": "Curaçao",
      "Owner A": null,
      "Team B": "Côte d'Ivoire",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 56,
      "Date": "2026-06-25",
      "Group": "Group E",
      "Team A": "Ecuador",
      "Owner A": null,
      "Team B": "Germany",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 57,
      "Date": "2026-06-25",
      "Group": "Group F",
      "Team A": "Japan",
      "Owner A": null,
      "Team B": "Sweden",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 58,
      "Date": "2026-06-25",
      "Group": "Group F",
      "Team A": "Tunisia",
      "Owner A": null,
      "Team B": "Netherlands",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 59,
      "Date": "2026-06-25",
      "Group": "Group D",
      "Team A": "Türkiye",
      "Owner A": null,
      "Team B": "USA",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Los Angeles Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 60,
      "Date": "2026-06-25",
      "Group": "Group D",
      "Team A": "Paraguay",
      "Owner A": null,
      "Team B": "Australia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "San Francisco Bay Area Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 61,
      "Date": "2026-06-26",
      "Group": "Group I",
      "Team A": "Norway",
      "Owner A": null,
      "Team B": "France",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Boston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 62,
      "Date": "2026-06-26",
      "Group": "Group I",
      "Team A": "Senegal",
      "Owner A": null,
      "Team B": "Iraq",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Toronto Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 63,
      "Date": "2026-06-26",
      "Group": "Group G",
      "Team A": "Egypt",
      "Owner A": null,
      "Team B": "IR Iran",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Seattle Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 64,
      "Date": "2026-06-26",
      "Group": "Group G",
      "Team A": "New Zealand",
      "Owner A": null,
      "Team B": "Belgium",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "BC Place Vancouver",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 65,
      "Date": "2026-06-26",
      "Group": "Group H",
      "Team A": "Cabo Verde",
      "Owner A": null,
      "Team B": "Saudi Arabia",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Houston Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 66,
      "Date": "2026-06-26",
      "Group": "Group H",
      "Team A": "Uruguay",
      "Owner A": null,
      "Team B": "Spain",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Estadio Guadalajara",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 67,
      "Date": "2026-06-27",
      "Group": "Group L",
      "Team A": "Panama",
      "Owner A": null,
      "Team B": "England",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "New York New Jersey Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 68,
      "Date": "2026-06-27",
      "Group": "Group L",
      "Team A": "Croatia",
      "Owner A": null,
      "Team B": "Ghana",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Philadelphia Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 69,
      "Date": "2026-06-27",
      "Group": "Group J",
      "Team A": "Algeria",
      "Owner A": null,
      "Team B": "Austria",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Kansas City Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 70,
      "Date": "2026-06-27",
      "Group": "Group J",
      "Team A": "Jordan",
      "Owner A": null,
      "Team B": "Argentina",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Dallas Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 71,
      "Date": "2026-06-27",
      "Group": "Group K",
      "Team A": "Colombia",
      "Owner A": null,
      "Team B": "Portugal",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Miami Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    },
    {
      "Match #": 72,
      "Date": "2026-06-27",
      "Group": "Group K",
      "Team A": "Congo DR",
      "Owner A": null,
      "Team B": "Uzbekistan",
      "Owner B": null,
      "Player Matchup": " vs ",
      "Venue": "Atlanta Stadium",
      "Competition": "FIFA World Cup 2026 Finals",
      "Score A": null,
      "Score B": null,
      "Status": "Pending",
      "Team A Pts": 0,
      "Team B Pts": 0,
      "Count?": "No"
    }
  ],
  "matches": [
    {
      "Date": 46184.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Mexico",
      "Home Owner": "Ahad",
      "Home Goals": 2,
      "Away Goals": 0,
      "Away Owner": "Shafee",
      "Away Team": "South Africa",
      "DateISO": "2026-06-11T12:00:00"
    },
    {
      "Date": 46184.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "South Korea",
      "Home Owner": "Ahad",
      "Home Goals": 2,
      "Away Goals": 1,
      "Away Owner": "Sabir",
      "Away Team": "Czechia",
      "DateISO": "2026-06-11T19:00:00"
    },
    {
      "Date": 46185.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Canada",
      "Home Owner": "Shafee",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": null,
      "Away Team": "Bosnia-Herzegovina",
      "DateISO": "2026-06-12T12:00:00"
    },
    {
      "Date": 46185.75,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "United States",
      "Home Owner": "Hood",
      "Home Goals": 4,
      "Away Goals": 1,
      "Away Owner": "Shafee",
      "Away Team": "Paraguay",
      "DateISO": "2026-06-12T18:00:00"
    },
    {
      "Date": 46186.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Qatar",
      "Home Owner": "Shafee",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Hood",
      "Away Team": "Switzerland",
      "DateISO": "2026-06-13T12:00:00"
    },
    {
      "Date": 46186.625,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Brazil",
      "Home Owner": "Shahid",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Shoeb",
      "Away Team": "Morocco",
      "DateISO": "2026-06-13T15:00:00"
    },
    {
      "Date": 46186.75,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Haiti",
      "Home Owner": "Hood",
      "Home Goals": 0,
      "Away Goals": 1,
      "Away Owner": "Ahad",
      "Away Team": "Scotland",
      "DateISO": "2026-06-13T18:00:00"
    },
    {
      "Date": 46186.875,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Australia",
      "Home Owner": "Ehti",
      "Home Goals": 2,
      "Away Goals": 0,
      "Away Owner": "Shahid",
      "Away Team": "Turkey",
      "DateISO": "2026-06-13T21:00:00"
    },
    {
      "Date": 46187.41666666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Germany",
      "Home Owner": "Hood",
      "Home Goals": 7,
      "Away Goals": 1,
      "Away Owner": "Shoeb",
      "Away Team": "Curaçao",
      "DateISO": "2026-06-14T10:00:00"
    },
    {
      "Date": 46187.54166666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Netherlands",
      "Home Owner": "Ahad",
      "Home Goals": 2,
      "Away Goals": 2,
      "Away Owner": "Shoeb",
      "Away Team": "Japan",
      "DateISO": "2026-06-14T13:00:00"
    },
    {
      "Date": 46187.66666666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Ivory Coast",
      "Home Owner": "Rasy",
      "Home Goals": 1,
      "Away Goals": 0,
      "Away Owner": "Shahid",
      "Away Team": "Ecuador",
      "DateISO": "2026-06-14T16:00:00"
    },
    {
      "Date": 46187.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Sweden",
      "Home Owner": "Ahad",
      "Home Goals": 5,
      "Away Goals": 1,
      "Away Owner": "Ehti",
      "Away Team": "Tunisia",
      "DateISO": "2026-06-14T19:00:00"
    },
    {
      "Date": 46188.375,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Spain",
      "Home Owner": "Shoeb",
      "Home Goals": 0,
      "Away Goals": 0,
      "Away Owner": "Rasy",
      "Away Team": "Cape Verde",
      "DateISO": "2026-06-15T09:00:00"
    },
    {
      "Date": 46188.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Belgium",
      "Home Owner": "Shahid",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Rasy",
      "Away Team": "Egypt",
      "DateISO": "2026-06-15T12:00:00"
    },
    {
      "Date": 46188.625,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Saudi Arabia",
      "Home Owner": "Ehti",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Shahid",
      "Away Team": "Uruguay",
      "DateISO": "2026-06-15T15:00:00"
    },
    {
      "Date": 46188.75,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Iran",
      "Home Owner": "Ehti",
      "Home Goals": 2,
      "Away Goals": 2,
      "Away Owner": "Sabir",
      "Away Team": "New Zealand",
      "DateISO": "2026-06-15T18:00:00"
    },
    {
      "Date": 46189.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "France",
      "Home Owner": "Ehti",
      "Home Goals": 3,
      "Away Goals": 1,
      "Away Owner": "Sabir",
      "Away Team": "Senegal",
      "DateISO": "2026-06-16T12:00:00"
    },
    {
      "Date": 46189.625,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Iraq",
      "Home Owner": "Sabir",
      "Home Goals": 1,
      "Away Goals": 4,
      "Away Owner": "Ahad",
      "Away Team": "Norway",
      "DateISO": "2026-06-16T15:00:00"
    },
    {
      "Date": 46189.75,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Argentina",
      "Home Owner": "Rasy",
      "Home Goals": 3,
      "Away Goals": 0,
      "Away Owner": "Shafee",
      "Away Team": "Algeria",
      "DateISO": "2026-06-16T18:00:00"
    },
    {
      "Date": 46189.875,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Austria",
      "Home Owner": "Shahid",
      "Home Goals": 3,
      "Away Goals": 1,
      "Away Owner": "Hood",
      "Away Team": "Jordan",
      "DateISO": "2026-06-16T21:00:00"
    },
    {
      "Date": 46190.41666666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Portugal",
      "Home Owner": "Sabir",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Ehti",
      "Away Team": "Congo",
      "DateISO": "2026-06-17T10:00:00"
    },
    {
      "Date": 46190.54166666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "England",
      "Home Owner": "Hood",
      "Home Goals": 4,
      "Away Goals": 2,
      "Away Owner": "Sabir",
      "Away Team": "Croatia",
      "DateISO": "2026-06-17T13:00:00"
    },
    {
      "Date": 46190.66666666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Ghana",
      "Home Owner": "Shoeb",
      "Home Goals": 1,
      "Away Goals": 0,
      "Away Owner": "Rasy",
      "Away Team": "Panama",
      "DateISO": "2026-06-17T16:00:00"
    },
    {
      "Date": 46190.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Uzbekistan",
      "Home Owner": "Shafee",
      "Home Goals": 1,
      "Away Goals": 3,
      "Away Owner": "Shoeb",
      "Away Team": "Colombia",
      "DateISO": "2026-06-17T19:00:00"
    },
    {
      "Date": 46191.375,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Czechia",
      "Home Owner": "Sabir",
      "Home Goals": 1,
      "Away Goals": 1,
      "Away Owner": "Shafee",
      "Away Team": "South Africa",
      "DateISO": "2026-06-18T09:00:00"
    },
    {
      "Date": 46191.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Switzerland",
      "Home Owner": "Hood",
      "Home Goals": 4,
      "Away Goals": 1,
      "Away Owner": null,
      "Away Team": "Bosnia-Herzegovina",
      "DateISO": "2026-06-18T12:00:00"
    },
    {
      "Date": 46191.625,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Canada",
      "Home Owner": "Shafee",
      "Home Goals": 6,
      "Away Goals": 0,
      "Away Owner": "Shafee",
      "Away Team": "Qatar",
      "DateISO": "2026-06-18T15:00:00"
    },
    {
      "Date": 46191.75,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Mexico",
      "Home Owner": "Ahad",
      "Home Goals": 1,
      "Away Goals": 0,
      "Away Owner": "Ahad",
      "Away Team": "South Korea",
      "DateISO": "2026-06-18T18:00:00"
    },
    {
      "Date": 46192.5,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "United States",
      "Home Owner": "Hood",
      "Home Goals": 2,
      "Away Goals": 0,
      "Away Owner": "Ehti",
      "Away Team": "Australia",
      "DateISO": "2026-06-19T12:00:00"
    },
    {
      "Date": 46192.625,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Scotland",
      "Home Owner": "Ahad",
      "Home Goals": 0,
      "Away Goals": 1,
      "Away Owner": "Shoeb",
      "Away Team": "Morocco",
      "DateISO": "2026-06-19T15:00:00"
    },
    {
      "Date": 46192.72916666667,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Brazil",
      "Home Owner": "Shahid",
      "Home Goals": 3,
      "Away Goals": 0,
      "Away Owner": "Hood",
      "Away Team": "Haiti",
      "DateISO": "2026-06-19T17:30:00"
    },
    {
      "Date": 46192.83333333333,
      "Stage": "GROUP_STAGE",
      "Status": "FINISHED",
      "Home Team": "Turkey",
      "Home Owner": "Shahid",
      "Home Goals": 0,
      "Away Goals": 1,
      "Away Owner": "Shafee",
      "Away Team": "Paraguay",
      "DateISO": "2026-06-19T20:00:00"
    },
    {
      "Date": 46193.41666666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Netherlands",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Sweden",
      "DateISO": "2026-06-20T10:00:00"
    },
    {
      "Date": 46193.54166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Germany",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Ivory Coast",
      "DateISO": "2026-06-20T13:00:00"
    },
    {
      "Date": 46193.70833333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Ecuador",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Curaçao",
      "DateISO": "2026-06-20T17:00:00"
    },
    {
      "Date": 46193.875,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Tunisia",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Japan",
      "DateISO": "2026-06-20T21:00:00"
    },
    {
      "Date": 46194.375,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Spain",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Saudi Arabia",
      "DateISO": "2026-06-21T09:00:00"
    },
    {
      "Date": 46194.5,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Belgium",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Iran",
      "DateISO": "2026-06-21T12:00:00"
    },
    {
      "Date": 46194.625,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Uruguay",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Cape Verde",
      "DateISO": "2026-06-21T15:00:00"
    },
    {
      "Date": 46194.75,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "New Zealand",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Egypt",
      "DateISO": "2026-06-21T18:00:00"
    },
    {
      "Date": 46195.41666666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Argentina",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Austria",
      "DateISO": "2026-06-22T10:00:00"
    },
    {
      "Date": 46195.58333333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "France",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Iraq",
      "DateISO": "2026-06-22T14:00:00"
    },
    {
      "Date": 46195.70833333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Norway",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Senegal",
      "DateISO": "2026-06-22T17:00:00"
    },
    {
      "Date": 46195.83333333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Jordan",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Algeria",
      "DateISO": "2026-06-22T20:00:00"
    },
    {
      "Date": 46196.41666666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Portugal",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Uzbekistan",
      "DateISO": "2026-06-23T10:00:00"
    },
    {
      "Date": 46196.54166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "England",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Ghana",
      "DateISO": "2026-06-23T13:00:00"
    },
    {
      "Date": 46196.66666666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Panama",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Croatia",
      "DateISO": "2026-06-23T16:00:00"
    },
    {
      "Date": 46196.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Colombia",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Congo",
      "DateISO": "2026-06-23T19:00:00"
    },
    {
      "Date": 46197.5,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Switzerland",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Canada",
      "DateISO": "2026-06-24T12:00:00"
    },
    {
      "Date": 46197.5,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Bosnia-Herzegovina",
      "Home Owner": null,
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Qatar",
      "DateISO": "2026-06-24T12:00:00"
    },
    {
      "Date": 46197.625,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Morocco",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "Haiti",
      "DateISO": "2026-06-24T15:00:00"
    },
    {
      "Date": 46197.625,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Scotland",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Brazil",
      "DateISO": "2026-06-24T15:00:00"
    },
    {
      "Date": 46197.75,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Czechia",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Mexico",
      "DateISO": "2026-06-24T18:00:00"
    },
    {
      "Date": 46197.75,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "South Africa",
      "Home Owner": "Shafee",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "South Korea",
      "DateISO": "2026-06-24T18:00:00"
    },
    {
      "Date": 46198.54166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Ecuador",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "Germany",
      "DateISO": "2026-06-25T13:00:00"
    },
    {
      "Date": 46198.54166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Curaçao",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Ivory Coast",
      "DateISO": "2026-06-25T13:00:00"
    },
    {
      "Date": 46198.66666666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Tunisia",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Netherlands",
      "DateISO": "2026-06-25T16:00:00"
    },
    {
      "Date": 46198.66666666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Japan",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ahad",
      "Away Team": "Sweden",
      "DateISO": "2026-06-25T16:00:00"
    },
    {
      "Date": 46198.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Turkey",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "United States",
      "DateISO": "2026-06-25T19:00:00"
    },
    {
      "Date": 46198.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Paraguay",
      "Home Owner": "Shafee",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Australia",
      "DateISO": "2026-06-25T19:00:00"
    },
    {
      "Date": 46199.5,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Norway",
      "Home Owner": "Ahad",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "France",
      "DateISO": "2026-06-26T12:00:00"
    },
    {
      "Date": 46199.5,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Senegal",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Iraq",
      "DateISO": "2026-06-26T12:00:00"
    },
    {
      "Date": 46199.70833333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Uruguay",
      "Home Owner": "Shahid",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Spain",
      "DateISO": "2026-06-26T17:00:00"
    },
    {
      "Date": 46199.70833333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Cape Verde",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Saudi Arabia",
      "DateISO": "2026-06-26T17:00:00"
    },
    {
      "Date": 46199.83333333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "New Zealand",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Belgium",
      "DateISO": "2026-06-26T20:00:00"
    },
    {
      "Date": 46199.83333333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Egypt",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Ehti",
      "Away Team": "Iran",
      "DateISO": "2026-06-26T20:00:00"
    },
    {
      "Date": 46200.58333333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Panama",
      "Home Owner": "Rasy",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Hood",
      "Away Team": "England",
      "DateISO": "2026-06-27T14:00:00"
    },
    {
      "Date": 46200.58333333333,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Croatia",
      "Home Owner": "Sabir",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shoeb",
      "Away Team": "Ghana",
      "DateISO": "2026-06-27T14:00:00"
    },
    {
      "Date": 46200.6875,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Colombia",
      "Home Owner": "Shoeb",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Sabir",
      "Away Team": "Portugal",
      "DateISO": "2026-06-27T16:30:00"
    },
    {
      "Date": 46200.6875,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Congo",
      "Home Owner": "Ehti",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shafee",
      "Away Team": "Uzbekistan",
      "DateISO": "2026-06-27T16:30:00"
    },
    {
      "Date": 46200.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Jordan",
      "Home Owner": "Hood",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Rasy",
      "Away Team": "Argentina",
      "DateISO": "2026-06-27T19:00:00"
    },
    {
      "Date": 46200.79166666667,
      "Stage": "GROUP_STAGE",
      "Status": "TIMED",
      "Home Team": "Algeria",
      "Home Owner": "Shafee",
      "Home Goals": null,
      "Away Goals": null,
      "Away Owner": "Shahid",
      "Away Team": "Austria",
      "DateISO": "2026-06-27T19:00:00"
    }
  ]
};
